# Generated by Django 2.1.5 on 2020-10-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    
    dependencies = [
        ('accounts', '0002_remove_profile_avatar'),
    ]

    operations = [
    ]
