# Generated by Django 2.1.5 on 2020-10-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    
    dependencies = [
        ('questions', '0003_auto_20201010_2050'),
    ]

    operations = [
    ]
